In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import datetime as dt

In [2]:
raw_data = pd.read_csv('Information Technology.csv', sep='\s*,\s*',
                           header=0, encoding='ascii', engine='python')

In [3]:
raw_data.head(10)

,Unnamed: 0,date,open,high,low,close,volume,Name,full_name,sector
0,1259,2/8/2013,67.7142,68.4014,66.8928,67.8542,158168416,AAPL,Apple Inc.,Information Technology
1,1260,2/11/2013,68.0714,69.2771,67.6071,68.5614,129029425,AAPL,Apple Inc.,Information Technology
2,1261,2/12/2013,68.5014,68.9114,66.8205,66.8428,151829363,AAPL,Apple Inc.,Information Technology
3,1262,2/13/2013,66.7442,67.6628,66.1742,66.7156,118721995,AAPL,Apple Inc.,Information Technology
4,1263,2/14/2013,66.3599,67.3771,66.2885,66.6556,88809154,AAPL,Apple Inc.,Information Technology
5,1264,2/15/2013,66.9785,67.1656,65.7028,65.7371,97924631,AAPL,Apple Inc.,Information Technology
6,1265,2/19/2013,65.8714,66.1042,64.8356,65.7128,108854046,AAPL,Apple Inc.,Information Technology
7,1266,2/20/2013,65.3842,65.3842,64.1142,64.1214,118891367,AAPL,Apple Inc.,Information Technology
8,1267,2/21/2013,63.7142,64.1671,63.2599,63.7228,111596821,AAPL,Apple Inc.,Information Technology
9,1268,2/22/2013,64.1785,64.5142,63.7999,64.4014,82583823,AAPL,Apple Inc.,Information Technology

## If we want to take a more long-term approach to assessing the performance of a strategy, we can use rolling returns to determine a percentage-based return on any given stock after X years.

In [4]:
raw_data

,Unnamed: 0,date,open,high,low,close,volume,Name,full_name,sector
0,1259,2/8/2013,67.7142,68.4014,66.8928,67.8542,158168416,AAPL,Apple Inc.,Information Technology
1,1260,2/11/2013,68.0714,69.2771,67.6071,68.5614,129029425,AAPL,Apple Inc.,Information Technology
2,1261,2/12/2013,68.5014,68.9114,66.8205,66.8428,151829363,AAPL,Apple Inc.,Information Technology
3,1262,2/13/2013,66.7442,67.6628,66.1742,66.7156,118721995,AAPL,Apple Inc.,Information Technology
4,1263,2/14/2013,66.3599,67.3771,66.2885,66.6556,88809154,AAPL,Apple Inc.,Information Technology
5,1264,2/15/2013,66.9785,67.1656,65.7028,65.7371,97924631,AAPL,Apple Inc.,Information Technology
6,1265,2/19/2013,65.8714,66.1042,64.8356,65.7128,108854046,AAPL,Apple Inc.,Information Technology
7,1266,2/20/2013,65.3842,65.3842,64.1142,64.1214,118891367,AAPL,Apple Inc.,Information Technology
8,1267,2/21/2013,63.7142,64.1671,63.2599,63.7228,111596821,AAPL,Apple Inc.,Information Technology
9,1268,2/22/2013,64.1785,64.5142,63.7999,64.4014,82583823,AAPL,Apple Inc.,Information Technology
10,1269,2/25/2013,64.8356,65.0171,63.2242,63.2571,92899597,AAPL,Apple Inc.,Information Technology
11,1270,2/26/2013,63.4028,64.5056,62.5228,64.1385,125096657,AAPL,Apple Inc.,Information Technology
12,1271,2/27/2013,64.0614,64.6342,62.9499,63.5099,146674682,AAPL,Apple Inc.,Information Technology
13,1272,2/28/2013,63.4357,63.9814,63.0571,63.0571,80532382,AAPL,Apple Inc.,Information Technology
14,1273,3/1/2013,62.5714,62.5971,61.4257,61.4957,137899041,AAPL,Apple Inc.,Information Technology
15,1274,3/4/2013,61.1142,61.1714,59.8571,60.0071,145406366,AAPL,Apple Inc.,Information Technology
16,1275,3/5/2013,60.2114,62.1699,60.1071,61.5919,159298020,AAPL,Apple Inc.,Information Technology
17,1276,3/6/2013,62.0728,62.1785,60.6328,60.8088,114903180,AAPL,Apple Inc.,Information Technology
18,1277,3/7/2013,60.6428,61.7157,60.1514,61.5117,116992841,AAPL,Apple Inc.,Information Technology
19,1278,3/8/2013,61.3999,62.2042,61.2299,61.6742,97854442,AAPL,Apple Inc.,Information Technology
20,1279,3/11/2013,61.3928,62.7157,60.7342,62.5528,118272126,AAPL,Apple Inc.,Information Technology
21,1280,3/12/2013,62.2285,62.6971,61.0814,61.2042,116268341,AAPL,Apple Inc.,Information Technology
22,1281,3/13/2013,61.2071,62.0714,60.7657,61.1928,101369051,AAPL,Apple Inc.,Information Technology
23,1282,3/14/2013,61.8328,62.0914,61.4928,61.7857,75834906,AAPL,Apple Inc.,Information Technology
24,1283,3/15/2013,62.5614,63.4614,62.4642,63.3799,160710606,AAPL,Apple Inc.,Information Technology
25,1284,3/18/2013,63.0642,65.3514,63.0285,65.1028,150441144,AAPL,Apple Inc.,Information Technology
26,1285,3/19/2013,65.6428,65.8528,64.0714,64.9271,131531708,AAPL,Apple Inc.,Information Technology
27,1286,3/20/2013,65.3456,65.3756,64.2271,64.5828,77016849,AAPL,Apple Inc.,Information Technology
28,1287,3/21/2013,64.3171,65.4256,64.2999,64.6756,95493524,AAPL,Apple Inc.,Information Technology
29,1288,3/22/2013,64.9399,66.0142,64.7299,65.9871,98570591,AAPL,Apple Inc.,Information Technology
...,...,...,...,...,...,...,...,...,...,...
83634,603902,12/26/2017,29.5100,29.6902,29.3200,29.4100,1410761,XRX,Xerox Corp.,Information Technology
83635,603903,12/27/2017,29.4200,29.6900,29.3500,29.4800,908700,XRX,Xerox Corp.,Information Technology
83636,603904,12/28/2017,29.2500,29.4750,29.1100,29.4500,1032378,XRX,Xerox Corp.,Information Technology
83637,603905,12/29/2017,29.4000,29.4700,29.1200,29.1500,1537390,XRX,Xerox Corp.,Information Technology
83638,603906,1/2/2018,29.3800,29.4800,29.1100,29.3700,1776767,XRX,Xerox Corp.,Information Technology
83639,603907,1/3/2018,29.4100,29.4800,29.0200,29.3300,1907546,XRX,Xerox Corp.,Information Technology
83640,603908,1/4/2018,29.4700,29.7200,29.3350,29.6900,2565933,XRX,Xerox Corp.,Information Technology
83641,603909,1/5/2018,29.8000,29.9400,29.5500,29.9100,1542135,XRX,Xerox Corp.,Information Technology
83642,603910,1/8/2018,29.8900,30.2800,29.8700,30.2600,1282197,XRX,Xerox Corp.,Information Technology
83643,603911,1/9/2018,30.2800,30.5500,30.1500,30.1900,1585870,XRX,Xerox Corp.,Information Technology
83644,603912,1/10/2018,30.1700,30.3900,30.0300,30.3500,994900,XRX,Xerox Corp.,Information Technology
83645,603913,1/11/2018,31.9600,32.5100,31.2400,31.8600,4010188,XRX,Xerox Corp.,Information Technology
83646,603914,1/12/2018,31.7200,32.8400,31.6100,32.7700,3323902,XRX,Xerox Corp.,Information Technology
83647,603915,1/16/2018,32.8500,32.9700,32.2400,32.3500,1731522,XRX,Xerox Corp.,Information Technology
83648,603916,1/17/2018,32.4300,32.4300,31.8600,31.9200,1724827,XRX,Xerox Corp.,Information Technology
83649,603917,1/18/2018,31.8200,31.8300,31.3100,31.3700,1528292,XRX,Xerox Corp.,Information Technology
83650,603918,1/19/2018,31.4700,31.8900,31.3050,31.8000,1578866,XRX,Xerox Corp.,Information Technology
83651,603919,1/22/2018,32.6400,33.0800,32.0750,32.6400,3574627,XRX,Xerox Corp.,Information Technology
83652,603920,1/23/2018,32.5700,32.7400,32.2000,32.5800,1532980,XRX,Xerox Corp.,Information Technology
83653,603921,1/24/2018,32.6600,32.6700,32.2500,32.3600,1676853,XRX,Xerox Corp.,Information Technology
83654,603922,1/25/2018,32.4800,32.5400,32.1200,32.3800,1479103,XRX,Xerox Corp.,Information Technology
83655,603923,1/26/2018,32.7600,32.8800,32.4300,32.8300,2086851,XRX,Xerox Corp.,Information Technology
83656,603924,1/29/2018,32.7900,32.9700,32.6900,32.8400,1222781,XRX,Xerox Corp.,Information Technology
83657,603925,1/30/2018,32.6200,32.8400,32.2600,32.6800,2213009,XRX,Xerox Corp.,Information Technology
83658,603926,1/31/2018,33.8800,37.4200,33.6000,34.1300,17964257,XRX,Xerox Corp.,Information Technology
83659,603927,2/1/2018,34.1000,34.3300,32.5600,32.7500,8154921,XRX,Xerox Corp.,Information Technology
83660,603928,2/2/2018,32.5100,32.5100,31.5350,31.6300,3526028,XRX,Xerox Corp.,Information Technology
83661,603929,2/5/2018,31.8000,32.6800,31.3800,31.3800,4104575,XRX,Xerox Corp.,Information Technology
83662,603930,2/6/2018,30.9400,31.5300,30.2200,30.8500,4431244,XRX,Xerox Corp.,Information Technology
83663,603931,2/7/2018,30.7300,31.4050,30.7300,31.1800,2983504,XRX,Xerox Corp.,Information Technology

In [5]:
apple = raw_data[raw_data['Name'] == 'AAPL']

In [ ]:
apple

In [9]:
dataframe1=apple[apple['date'].dt.year == 2015]

In [10]:
apple['date'] = pd.to_datetime(apple['date'])

data_2013 = apple[apple['date'].dt.year == 2013]
data_2014 = apple[apple['date'].dt.year == 2014]
data_2015 = apple[apple['date'].dt.year == 2015]
data_2016 = apple[apple['date'].dt.year == 2016]
data_2017 = apple[apple['date'].dt.year == 2017]

C:\Users\sharfaraz\AppData\Roaming\Python\Python36\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [11]:
diff_2013 = (data_2013.iloc[-1].close - data_2013.iloc[0].close) / data_2013.iloc[0].close
diff_2014 = (data_2014.iloc[-1].close - data_2014.iloc[0].close) / data_2014.iloc[0].close
diff_2015 = (data_2015.iloc[-1].close - data_2015.iloc[0].close) / data_2015.iloc[0].close
diff_2016 = (data_2016.iloc[-1].close - data_2016.iloc[0].close) / data_2016.iloc[0].close
diff_2017 = (data_2017.iloc[-1].close - data_2017.iloc[0].close) / data_2017.iloc[0].close
five_year_return = (diff_2013 + diff_2014 + diff_2015 + diff_2016 + diff_2017) / 5 * 100
print(diff_2013 * 100)
print(diff_2014 * 100)
print(diff_2015 * 100)
print(diff_2016 * 100)
print(diff_2017 * 100)
print('Five-year return for Apple:',five_year_return, '%')

18.1144276994
39.6888070515
-3.72267447178
9.93830090176
45.6995264744
Five-year return for Apple: 21.9436775311 %

In [12]:
base_yr = 2013 
counter = 0 
years_arr = pd.DataFrame()
while counter < 5:
    year = [] 
    year = apple.loc[dt.date(year = 2013, month = 1, day = 1):dt.date(year = 2013, month = 12, day = 31)]
    print(year)
    counter = counter + 1

TypeError: '>' not supported between instances of 'int' and 'datetime.date'